In [ ]:
# Use the file heights_weights.csv (https://raw.githubusercontent.com/Jovita7/Data-Analysis-and-
# Visualization/main/heights_weights.csv) which contains 10000 non-null values for heights and weights. The Male column shows
# 1 if the person is a Male and 0 if the person is a Female.
# 1. Convert this file into a pandas Data Frame. (0.5 marks)
# 2. Display basic information like memory and data types for this data frame. (0.5 marks)
# 3. Display basic statistics like mean, std, quartiles, etc. for this data frame. (0.5 marks)
# 4. Create a correlation table for the data frame and comment about what kind of correlation is there between Height and
# Weight. (0.5 marks)
# 5. Do Height and Weight contain any outliers? (1 mark)

In [ ]:
import pandas as pd
# Convert this file into a pandas Data Frame. (0.5 marks)
df=pd.read_csv("heights_weights.csv")
df

         Height      Weight  Male
0     73.847017  241.893563     1
1     68.781904  162.310473     1
2     74.110105  212.740856     1
3     71.730978  220.042470     1
4     69.881796  206.349801     1
...         ...         ...   ...
9995  66.172652  136.777454     0
9996  67.067155  170.867906     0
9997  63.867992  128.475319     0
9998  69.034243  163.852461     0
9999  61.944246  113.649103     0

[10000 rows x 3 columns]

In [3]:
# 2. Display basic information like memory and data types for this data frame. (0.5 marks)
x1=df.info()
x1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Height  10000 non-null  float64
 1   Weight  10000 non-null  float64
 2   Male    10000 non-null  int64
dtypes: float64(2), int64(1)
memory usage: 234.5 KB

In [4]:
# 3. Display basic statistics like mean, std, quartiles, etc. for this data frame. (0.5 marks)
x2=df.describe()
x2

             Height        Weight          Male
count  10000.000000  10000.000000  10000.000000
mean      66.367560    161.440357      0.500000
std        3.847528     32.108439      0.500025
min       54.263133     64.700127      0.000000
25%       63.505620    135.818051      0.000000
50%       66.318070    161.212928      0.500000
75%       69.174262    187.169525      1.000000
max       78.998742    269.989699      1.000000

In [5]:
# 4. Create a correlation table for the data frame and comment about what kind of correlation is there between Height and
# Weight. (0.5 marks)
x2=df["Height"].corr(df["Weight"])
x2

np.float64(0.9247562987409148)

In [8]:
# 5. Do Height and Weight contain any outliers? (1 mark)
Q1=df["Height"].quantile(0.25)
Q3=df["Weight"].quantile(0.75)
Q1,Q3

(np.float64(63.505620481218955), np.float64(187.16952486868348))

In [9]:
IQR=Q3-Q1
IQR

np.float64(123.66390438746453)

In [12]:
lower_bound=Q1-1.5*IQR
higher_bound=Q3+1.5*IQR
lower_bound,higher_bound

(np.float64(-121.99023609997784), np.float64(372.6653814498803))

In [15]:
jesus=df[(df["Height"]>lower_bound)|(df["Weight"]<higher_bound)]
jesus,"Contain outliners"

(         Height      Weight  Male
 0     73.847017  241.893563     1
 1     68.781904  162.310473     1
 2     74.110105  212.740856     1
 3     71.730978  220.042470     1
 4     69.881796  206.349801     1
 ...         ...         ...   ...
 9995  66.172652  136.777454     0
 9996  67.067155  170.867906     0
 9997  63.867992  128.475319     0
 9998  69.034243  163.852461     0
 9999  61.944246  113.649103     0

 [10000 rows x 3 columns],
 'Contain outliners')