In [1]:
# Use the file movies.csv which contains 1629 rows and 18 columns. Read this csv file and display the basic information like
# memory and data types for this data frame.
# Write python code for the following cases:
# 1. List out Movies Released in Year 2019.
# 2. How Many Movies are having IMDB Ra􀆟ng > 7 (Display Number of Movies).
# 3. List out the Movies with ‘􀆟tle’ and ‘story’ whose IMDB Votes > 20000.
# 4. List out Movies Released in Year 2018, Display only Movie Title with Release Date of Year 2018 Movies.
# 5. Display only Movie Title with its Wikipedia Link.

In [2]:
import pandas as pd
df=pd.read_csv("movie_dataset.csv")
df

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,4798,220000,Action Crime Thriller,NaN,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4799,4799,9000,Comedy Romance,NaN,72766,NaN,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4800,4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4801,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
4802,4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [11]:
# 2. How Many Movies are having IMDB Ra􀆟ng > 7 (Display Number of Movies).
df1=df[df["vote_average"]>7]
df1.shape[0]

809

In [13]:
# 3. List out the Movies with ‘􀆟tle’ and ‘story’ whose IMDB Votes > 20000.
df2=df[df['vote_count']>2000]
df2

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4291,4291,1200000,Horror Mystery Crime,NaN,176,shotgun based on short film sadist pistol chained,en,Saw,Obsessed with teaching his victims the value o...,63.655973,...,103.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Live or die. Make your choice.,Saw,7.2,2184,Cary Elwes Danny Glover Monica Potter Michael ...,"[{'name': 'James Wan', 'gender': 2, 'departmen...",James Wan
4300,4300,1200000,Crime Thriller,NaN,500,traitor jewelry psychopath thief heist,en,Reservoir Dogs,A botched robbery indicates a police informant...,66.925866,...,99.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Every dog has his day.,Reservoir Dogs,8.0,3697,Harvey Keitel Tim Roth Michael Madsen Chris Pe...,"[{'name': 'Quentin Tarantino', 'gender': 2, 'd...",Quentin Tarantino
4302,4302,1200000,Western,"http://www.mgm.com/#/our-titles/766/The-Good,-...",429,bounty hunter refugee gold anti hero gallows,it,"Il buono, il brutto, il cattivo",While the Civil War rages between the Union an...,88.377076,...,161.0,"[{""iso_639_1"": ""it"", ""name"": ""Italiano""}]",Released,For three men the Civil War wasn't hell. It wa...,"The Good, the Bad and the Ugly",8.1,2311,Eli Wallach Clint Eastwood Lee Van Cleef Aldo ...,"[{'name': 'Gray Frederickson', 'gender': 2, 'd...",Sergio Leone
4337,4337,1300000,Crime Drama,NaN,103,vietnam veteran taxi obsession drug dealer nig...,en,Taxi Driver,A mentally unstable Vietnam War veteran works ...,58.845025,...,114.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"On every street in every city, there's a nobod...",Taxi Driver,8.0,2535,Robert De Niro Cybill Shepherd Harvey Keitel J...,"[{'name': 'Bernard Herrmann', 'gender': 2, 'de...",Martin Scorsese
4602,4602,350000,Drama,NaN,389,judge jurors sultriness death penalty father m...,en,12 Angry Men,The defense and the prosecution have rested an...,59.259204,...,96.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Life is in their hands. Death is on their minds.,12 Angry Men,8.2,2078,Henry Fonda Martin Balsam John Fiedler Lee J. ...,"[{'name': 'Henry Fonda', 'gender': 2, 'departm...",Sidney Lumet

In [24]:
# 5. Display only Movie Title with its Wikipedia Link.
df3=df[["original_title","homepage"]]
df3

,original_title,homepage
0,Avatar,http://www.avatarmovie.com/
1,Pirates of the Caribbean: At World's End,http://disney.go.com/disneypictures/pirates/
2,Spectre,http://www.sonypictures.com/movies/spectre/
3,The Dark Knight Rises,http://www.thedarkknightrises.com/
4,John Carter,http://movies.disney.com/john-carter
...,...,...
4798,El Mariachi,NaN
4799,Newlyweds,NaN
4800,"Signed, Sealed, Delivered",http://www.hallmarkchannel.com/signedsealeddel...
4801,Shanghai Calling,http://shanghaicalling.com/
4802,My Date with Drew,NaN