In [5]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')
print(df)

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [6]:
# Write a Pandas program to read a dataset from diamonds DataFrame and modify the default columns values and print the first 6 rows.
first6row=df.head(6)
first6row

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48

In [7]:
# Write a Pandas program to select a series from diamonds DataFrame. Print the content of the series.
jesus=df['color']
jesus

0        E
1        E
2        E
3        I
4        J
        ..
53935    D
53936    D
53937    D
53938    H
53939    D
Name: color, Length: 53940, dtype: object

In [8]:
# Create a New 'Quality -color' Series
# Write a Pandas program to create a new 'Quality-color' Series (use bracket notation to define the Series name) of the diamonds DataFrame.

df['Quality-color']=df['cut']+" "+df.color
df

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,Ideal E
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium E
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good E
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium I
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good J
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,Ideal D
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,Good D
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,Very Good D
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,Premium H
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,Ideal D

In [9]:
# Count Rows, Columns, and Data Types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   carat          53940 non-null  float64
 1   cut            53940 non-null  object
 2   color          53940 non-null  object
 3   clarity        53940 non-null  object
 4   depth          53940 non-null  float64
 5   table          53940 non-null  float64
 6   price          53940 non-null  int64
 7   x              53940 non-null  float64
 8   y              53940 non-null  float64
 9   z              53940 non-null  float64
 10  Quality-color  53940 non-null  object
dtypes: float64(6), int64(1), object(4)
memory usage: 4.5+ MB

In [10]:
# Write a Pandas program to summarize only 'object' columns of the diamonds Dataframe.
df.select_dtypes(include=['object']).columns

Index(['cut', 'color', 'clarity', 'Quality-color'], dtype='object')

In [11]:
# Write a Pandas program to remove multiple columns at once of the diamonds Dataframe.
df.drop(columns=['depth','table'])

       carat        cut color clarity  price     x     y     z Quality-color
0       0.23      Ideal     E     SI2    326  3.95  3.98  2.43       Ideal E
1       0.21    Premium     E     SI1    326  3.89  3.84  2.31     Premium E
2       0.23       Good     E     VS1    327  4.05  4.07  2.31        Good E
3       0.29    Premium     I     VS2    334  4.20  4.23  2.63     Premium I
4       0.31       Good     J     SI2    335  4.34  4.35  2.75        Good J
...      ...        ...   ...     ...    ...   ...   ...   ...           ...
53935   0.72      Ideal     D     SI1   2757  5.75  5.76  3.50       Ideal D
53936   0.72       Good     D     SI1   2757  5.69  5.75  3.61        Good D
53937   0.70  Very Good     D     SI1   2757  5.66  5.68  3.56   Very Good D
53938   0.86    Premium     H     SI2   2757  6.15  6.12  3.74     Premium H
53939   0.75      Ideal     D     SI2   2757  5.83  5.87  3.64       Ideal D

[53940 rows x 9 columns]

In [12]:
# Write a Pandas program to remove the second column of the diamonds Dataframe.
df.drop(df.columns[:2],axis=1)

      color clarity  depth  table  price     x     y     z Quality-color
0         E     SI2   61.5   55.0    326  3.95  3.98  2.43       Ideal E
1         E     SI1   59.8   61.0    326  3.89  3.84  2.31     Premium E
2         E     VS1   56.9   65.0    327  4.05  4.07  2.31        Good E
3         I     VS2   62.4   58.0    334  4.20  4.23  2.63     Premium I
4         J     SI2   63.3   58.0    335  4.34  4.35  2.75        Good J
...     ...     ...    ...    ...    ...   ...   ...   ...           ...
53935     D     SI1   60.8   57.0   2757  5.75  5.76  3.50       Ideal D
53936     D     SI1   63.1   55.0   2757  5.69  5.75  3.61        Good D
53937     D     SI1   62.8   60.0   2757  5.66  5.68  3.56   Very Good D
53938     H     SI2   61.0   58.0   2757  6.15  6.12  3.74     Premium H
53939     D     SI2   62.2   55.0   2757  5.83  5.87  3.64       Ideal D

[53940 rows x 9 columns]

In [13]:
# Write a Pandas program to rename all the columns of the diamonds Dataframe.
df.rename(columns={'color':'Jesus','clarity':"Christ"})

,carat,cut,Jesus,Christ,depth,table,price,x,y,z,Quality-color
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,Ideal E
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium E
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good E
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium I
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good J
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,Ideal D
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,Good D
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,Very Good D
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,Premium H
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,Ideal D

In [14]:
df['carat'].astype(float)
df['carat'].replace(0.23, 1).head(10)

0    1.00
1    0.21
2    1.00
3    0.29
4    0.31
5    0.24
6    0.24
7    0.26
8    0.22
9    1.00
Name: carat, dtype: float64

In [15]:
# Write a Pandas program to remove multiple rows at once (axis=0 refers to rows) from diamonds dataframe.
df.drop(df.index[:1],axis=0)

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium E
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good E
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium I
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good J
5,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48,Very Good J
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,Ideal D
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,Good D
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,Very Good D
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,Premium H
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,Ideal D

In [16]:
# Write a Pandas program to calculate the multiply of length, width and depth for each cut of diamonds DataFrame.
df["Cal"] = df["x"] * df["y"] * df["z"]
df.groupby("cut")["Cal"].mean()

cut
Fair         164.950549
Good         136.257267
Ideal        115.394912
Premium      145.052128
Very Good    130.999722
Name: Cal, dtype: float64

In [17]:
# Write a Pandas program to merge two DataFrames on a single column.
color_info = pd.DataFrame({
    'color': ['E', 'I', 'J'],
    'rating': ['High', 'Medium', 'Low']
})

merged = df.merge(color_info, how='outer', indicator=True)
print(merged.head())

   carat        cut color clarity  depth  table  price     x     y     z  \
0   0.23  Very Good     D     VS2   60.5   61.0    357  3.96  3.97  2.40
1   0.23  Very Good     D     VS1   61.9   58.0    402  3.92  3.96  2.44
2   0.26  Very Good     D     VS2   60.8   59.0    403  4.13  4.16  2.52
3   0.26       Good     D     VS2   65.2   56.0    403  3.99  4.02  2.61
4   0.26       Good     D     VS1   58.4   63.0    403  4.19  4.24  2.46

  Quality-color        Cal rating     _merge
0   Very Good D  37.730880    NaN  left_only
1   Very Good D  37.876608    NaN  left_only
2   Very Good D  43.295616    NaN  left_only
3        Good D  41.863878    NaN  left_only
4        Good D  43.703376    NaN  left_only

In [18]:
# Sort the 'cut' Series in Ascending Order
df.sort_values(by='cut',ascending=True)

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color,Cal
3850,1.01,Fair,F,SI2,64.8,55.0,3477,6.37,6.26,4.10,Fair F,163.492420
51464,1.20,Fair,G,I1,66.6,57.0,2376,6.57,6.50,4.34,Fair G,185.339700
51466,0.90,Fair,G,SI2,65.4,57.0,2376,6.01,5.97,3.98,Fair G,142.801206
10237,1.26,Fair,D,SI2,64.5,59.0,4746,6.75,6.71,4.34,Fair D,196.569450
10760,1.01,Fair,E,SI1,69.5,55.0,4853,6.00,5.94,4.15,Fair E,147.906000
...,...,...,...,...,...,...,...,...,...,...,...,...
7402,0.33,Very Good,G,VS2,62.8,54.0,579,4.40,4.42,2.77,Very Good G,53.870960
43101,0.57,Very Good,E,SI2,58.8,57.3,1384,5.42,5.46,3.21,Very Good E,94.994172
16893,1.00,Very Good,G,VS2,62.2,58.0,6743,6.35,6.39,3.96,Very Good G,160.682940
16898,1.00,Very Good,D,VS2,59.6,60.0,6745,6.52,6.57,3.90,Very Good D,167.061960
21164,1.00,Very Good,E,VVS2,61.7,55.0,9324,6.38,6.42,3.95,Very Good E,161.790420

In [19]:
 # Sort the 'price' Series in Descending Order
df.sort_values(by='price',ascending=False)

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color,Cal
27749,2.29,Premium,I,VS2,60.8,60.0,18823,8.50,8.47,5.16,Premium I,371.494200
27748,2.00,Very Good,G,SI1,63.5,56.0,18818,7.90,7.97,5.04,Very Good G,317.333520
27747,1.51,Ideal,G,IF,61.7,55.0,18806,7.37,7.41,4.56,Ideal G,249.029352
27746,2.07,Ideal,G,SI2,62.5,55.0,18804,8.20,8.13,5.11,Ideal G,340.663260
27745,2.00,Very Good,H,SI1,62.8,57.0,18803,7.95,8.00,5.01,Very Good H,318.636000
...,...,...,...,...,...,...,...,...,...,...,...,...
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good J,51.917250
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium I,46.724580
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good E,38.076885
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium E,34.505856
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,Ideal E,38.202030

In [20]:
# Sort Entire DataFrame by 'carat' in Ascending and Descending Order
df.sort_values(by='carat',ascending=True)

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color,Cal
14,0.20,Premium,E,SI2,60.2,62.0,345,3.79,3.75,2.27,Premium E,32.262375
31597,0.20,Ideal,D,VS2,61.5,57.0,367,3.81,3.77,2.33,Ideal D,33.467421
31596,0.20,Premium,F,VS2,62.6,59.0,367,3.73,3.71,2.33,Premium F,32.243239
31595,0.20,Ideal,E,VS2,59.7,55.0,367,3.86,3.84,2.30,Ideal E,34.091520
31594,0.20,Premium,E,VS2,59.7,62.0,367,3.84,3.80,2.28,Premium E,33.269760
...,...,...,...,...,...,...,...,...,...,...,...,...
25998,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17,Premium I,631.894380
25999,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24,Premium J,621.496512
27130,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43,Fair H,633.355000
27630,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72,Fair J,698.455296
27415,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98,Fair J,790.133208

In [21]:
df.sort_values(by='carat',ascending=False)

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color,Cal
27415,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98,Fair J,790.133208
27630,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72,Fair J,698.455296
27130,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43,Fair H,633.355000
25999,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24,Premium J,621.496512
25998,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17,Premium I,631.894380
...,...,...,...,...,...,...,...,...,...,...,...,...
31593,0.20,Premium,E,VS2,61.1,59.0,367,3.81,3.78,2.32,Premium E,33.412176
31592,0.20,Premium,E,VS2,59.0,60.0,367,3.81,3.78,2.24,Premium E,32.260032
31599,0.20,Ideal,E,VS2,62.2,57.0,367,3.76,3.73,2.33,Ideal E,32.677784
31597,0.20,Ideal,D,VS2,61.5,57.0,367,3.81,3.77,2.33,Ideal D,33.467421
31598,0.20,Very Good,E,VS2,63.4,59.0,367,3.74,3.71,2.36,Very Good E,32.745944

In [22]:
# Filter Rows with Carat Weight at Least 0.3
df[df['carat']<=0.3]

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color,Cal
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,Ideal E,38.202030
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium E,34.505856
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good E,38.076885
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium I,46.724580
5,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48,Very Good J,38.693952
...,...,...,...,...,...,...,...,...,...,...,...,...
53635,0.30,Ideal,I,VVS1,62.1,56.0,552,4.30,4.33,2.68,Ideal I,49.898920
53636,0.30,Ideal,D,SI1,61.6,57.0,552,4.28,4.32,2.65,Ideal D,48.997440
53637,0.30,Very Good,D,SI1,62.5,57.0,552,4.26,4.28,2.67,Very Good D,48.681576
53638,0.30,Ideal,D,SI1,61.0,57.0,552,4.29,4.33,2.63,Ideal D,48.854091
53639,0.30,Ideal,D,SI1,61.0,56.0,552,4.35,4.37,2.66,Ideal D,50.565270

In [23]:
 # Convert Python List to Pandas Series
l=[1,2,3,4,5]
pd.Series(l)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [24]:
# Find Details of Diamonds Where x > 5, y > 5, and z > 5
df[((df['x']>5) & (df['y']>5) & (df['z']>5))]

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color,Cal
11778,1.83,Fair,J,I1,70.0,58.0,5083,7.34,7.28,5.12,Fair J,273.588224
13002,2.14,Fair,J,I1,69.4,57.0,5405,7.74,7.70,5.36,Fair J,319.445280
13118,2.15,Fair,J,I1,65.5,57.0,5430,8.01,7.95,5.23,Fair J,333.043785
13562,1.96,Fair,F,I1,66.6,60.0,5554,7.59,7.56,5.04,Fair F,289.197216
13757,2.22,Fair,J,I1,66.7,56.0,5607,8.04,8.02,5.36,Fair J,345.617088
...,...,...,...,...,...,...,...,...,...,...,...,...
27748,2.00,Very Good,G,SI1,63.5,56.0,18818,7.90,7.97,5.04,Very Good G,317.333520
27749,2.29,Premium,I,VS2,60.8,60.0,18823,8.50,8.47,5.16,Premium I,371.494200
48410,0.51,Very Good,E,VS1,61.8,54.7,1970,5.12,5.15,31.80,Very Good E,838.502400
49189,0.51,Ideal,E,VS1,61.8,55.0,2075,5.15,31.80,5.12,Ideal E,838.502400
49905,0.50,Very Good,G,VVS1,63.7,58.0,2180,5.01,5.04,5.06,Very Good G,127.767024

In [25]:
 # Find Diamonds That Are Either Premium or Ideal
df[((df['cut']=='Premium') | (df['cut']=='Ideal'))]

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color,Cal
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,Ideal E,38.202030
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium E,34.505856
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium I,46.724580
11,0.23,Ideal,J,VS1,62.8,56.0,340,3.93,3.90,2.46,Ideal J,37.704420
12,0.22,Premium,F,SI1,60.4,61.0,342,3.88,3.84,2.33,Premium F,34.715136
...,...,...,...,...,...,...,...,...,...,...,...,...
53931,0.71,Premium,F,SI1,59.8,62.0,2756,5.74,5.73,3.43,Premium F,112.813386
53934,0.72,Premium,D,SI1,62.7,59.0,2757,5.69,5.73,3.58,Premium D,116.721246
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,Ideal D,115.920000
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,Premium H,140.766120
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,Ideal D,124.568444

In [26]:
 # Find Diamonds with a Fair, Good, or Premium Cut
df[(df['cut']=='Fair') | (df['cut']=='Good') | (df['cut']=='Premium')]

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color,Cal
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium E,34.505856
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good E,38.076885
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium I,46.724580
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good J,51.917250
8,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49,Fair E,36.425214
...,...,...,...,...,...,...,...,...,...,...,...,...
53930,0.71,Premium,E,SI1,60.5,55.0,2756,5.79,5.74,3.49,Premium E,115.988754
53931,0.71,Premium,F,SI1,59.8,62.0,2756,5.74,5.73,3.43,Premium F,112.813386
53934,0.72,Premium,D,SI1,62.7,59.0,2757,5.69,5.73,3.58,Premium D,116.721246
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,Good D,118.110175
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,Premium H,140.766120

In [27]:
# Display All Column Labels
df.columns.tolist()

['carat',
 'cut',
 'color',
 'clarity',
 'depth',
 'table',
 'price',
 'x',
 'y',
 'z',
 'Quality-color',
 'Cal']

In [28]:
# Drop all non-numeric columns from diamonds DataFrame
df_numeric = df.select_dtypes(include=['number'])

print(df_numeric.head())

   carat  depth  table  price     x     y     z        Cal
0   0.23   61.5   55.0    326  3.95  3.98  2.43  38.202030
1   0.21   59.8   61.0    326  3.89  3.84  2.31  34.505856
2   0.23   56.9   65.0    327  4.05  4.07  2.31  38.076885
3   0.29   62.4   58.0    334  4.20  4.23  2.63  46.724580
4   0.31   63.3   58.0    335  4.34  4.35  2.75  51.917250

In [38]:
# Concatenate Diamonds DataFrame with the 'color' Series
pd.concat([df,df.color],axis=1).head()

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color,Cal,color
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,Ideal E,38.202030,E
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium E,34.505856,E
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good E,38.076885,E
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium I,46.724580,I
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good J,51.917250,J

In [43]:
# Read Specified Rows and All Columns
df.iloc[0,0:]

carat                0.23
cut                 Ideal
color                   E
clarity               SI2
depth                61.5
table                55.0
price                 326
x                    3.95
y                    3.98
z                    2.43
Quality-color     Ideal E
Cal              38.20203
Name: 0, dtype: object

In [48]:
 # Read Rows 0, 5, 7 and All Columns
df.iloc[[0,5,7],0::]

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color,Cal
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,Ideal E,38.202030
5,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48,Very Good J,38.693952
7,0.26,Very Good,H,SI1,61.9,55.0,337,4.07,4.11,2.53,Very Good H,42.321081

In [51]:
# Read Rows 2 Through 5 and All Columns
df.iloc[2:6,0::]

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color,Cal
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good E,38.076885
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium I,46.724580
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good J,51.917250
5,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48,Very Good J,38.693952

In [52]:
# Read Rows 0 Through 2 (Inclusive), Columns 'color' and 'price'
df.loc[0:2,['color','price']]

  color  price
0     E    326
1     E    326
2     E    327