In [3]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')
print(df)

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [7]:
# Write a Pandas program to read a dataset from diamonds DataFrame and modify the default columns values and print the first 6 rows.
first6row=df.head(6)
first6row

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48

In [15]:
# Write a Pandas program to select a series from diamonds DataFrame. Print the content of the series.
jesus=df['color']
jesus

0        E
1        E
2        E
3        I
4        J
        ..
53935    D
53936    D
53937    D
53938    H
53939    D
Name: color, Length: 53940, dtype: object

In [17]:
# Create a New 'Quality -color' Series
# Write a Pandas program to create a new 'Quality-color' Series (use bracket notation to define the Series name) of the diamonds DataFrame.

df['Quality-color']=df['cut']+" "+df.color
df

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,Ideal E
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium E
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good E
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium I
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good J
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,Ideal D
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,Good D
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,Very Good D
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,Premium H
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,Ideal D

In [18]:
# Count Rows, Columns, and Data Types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   carat          53940 non-null  float64
 1   cut            53940 non-null  object
 2   color          53940 non-null  object
 3   clarity        53940 non-null  object
 4   depth          53940 non-null  float64
 5   table          53940 non-null  float64
 6   price          53940 non-null  int64
 7   x              53940 non-null  float64
 8   y              53940 non-null  float64
 9   z              53940 non-null  float64
 10  Quality-color  53940 non-null  object
dtypes: float64(6), int64(1), object(4)
memory usage: 4.5+ MB

In [20]:
# Write a Pandas program to summarize only 'object' columns of the diamonds Dataframe.
df.select_dtypes(include=['object']).columns

Index(['cut', 'color', 'clarity', 'Quality-color'], dtype='object')

In [21]:
# Write a Pandas program to remove multiple columns at once of the diamonds Dataframe.
df.drop(columns=['depth','table'])

       carat        cut color clarity  price     x     y     z Quality-color
0       0.23      Ideal     E     SI2    326  3.95  3.98  2.43       Ideal E
1       0.21    Premium     E     SI1    326  3.89  3.84  2.31     Premium E
2       0.23       Good     E     VS1    327  4.05  4.07  2.31        Good E
3       0.29    Premium     I     VS2    334  4.20  4.23  2.63     Premium I
4       0.31       Good     J     SI2    335  4.34  4.35  2.75        Good J
...      ...        ...   ...     ...    ...   ...   ...   ...           ...
53935   0.72      Ideal     D     SI1   2757  5.75  5.76  3.50       Ideal D
53936   0.72       Good     D     SI1   2757  5.69  5.75  3.61        Good D
53937   0.70  Very Good     D     SI1   2757  5.66  5.68  3.56   Very Good D
53938   0.86    Premium     H     SI2   2757  6.15  6.12  3.74     Premium H
53939   0.75      Ideal     D     SI2   2757  5.83  5.87  3.64       Ideal D

[53940 rows x 9 columns]

In [25]:
# Write a Pandas program to remove the second column of the diamonds Dataframe.
df.drop(df.columns[:2],axis=1)

      color clarity  depth  table  price     x     y     z Quality-color
0         E     SI2   61.5   55.0    326  3.95  3.98  2.43       Ideal E
1         E     SI1   59.8   61.0    326  3.89  3.84  2.31     Premium E
2         E     VS1   56.9   65.0    327  4.05  4.07  2.31        Good E
3         I     VS2   62.4   58.0    334  4.20  4.23  2.63     Premium I
4         J     SI2   63.3   58.0    335  4.34  4.35  2.75        Good J
...     ...     ...    ...    ...    ...   ...   ...   ...           ...
53935     D     SI1   60.8   57.0   2757  5.75  5.76  3.50       Ideal D
53936     D     SI1   63.1   55.0   2757  5.69  5.75  3.61        Good D
53937     D     SI1   62.8   60.0   2757  5.66  5.68  3.56   Very Good D
53938     H     SI2   61.0   58.0   2757  6.15  6.12  3.74     Premium H
53939     D     SI2   62.2   55.0   2757  5.83  5.87  3.64       Ideal D

[53940 rows x 9 columns]

In [28]:
# Write a Pandas program to rename all the columns of the diamonds Dataframe.
df.rename(columns={'color':'Jesus','clarity':"Christ"})

,carat,cut,Jesus,Christ,depth,table,price,x,y,z,Quality-color
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,Ideal E
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium E
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good E
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium I
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good J
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,Ideal D
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,Good D
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,Very Good D
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,Premium H
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,Ideal D

In [50]:
df['carat'].astype(float)
df['carat'].replace(0.23, 1).head(10)

0    1.0
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
Name: carat, dtype: float64

In [38]:
# Write a Pandas program to remove multiple rows at once (axis=0 refers to rows) from diamonds dataframe.
df.drop(df.index[:1],axis=0)

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality-color
1,NaN,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium E
2,NaN,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good E
3,NaN,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium I
4,NaN,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good J
5,NaN,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48,Very Good J
...,...,...,...,...,...,...,...,...,...,...,...
53935,NaN,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,Ideal D
53936,NaN,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,Good D
53937,NaN,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,Very Good D
53938,NaN,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,Premium H
53939,NaN,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,Ideal D

In [58]:
# Write a Pandas program to calculate the multiply of length, width and depth for each cut of diamonds DataFrame.
df["Cal"] = df["x"] * df["y"] * df["z"]
df.groupby("cut")["Cal"].mean()

cut
Fair         164.950549
Good         136.257267
Ideal        115.394912
Premium      145.052128
Very Good    130.999722
Name: Cal, dtype: float64